# .github/workflows/ci-cd.yaml
name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . -t ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA
    - name: Login to GitHub Container Registry
      run: echo ${{secrets.GITHUB_TOKEN}} | docker login -u ${{github.actor}} --password-stdin ghcr.io
    - name: Push the Docker image to GitHub Container Registry
      run: docker push ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA
    - name: Deploy to Kubernetes
      uses: k8s-actions/kubectl@v1
      with:
        kubeconfig: ${{secrets.KUBECONFIG}}
        command: apply -f deployment.yaml --namespace=github-k8s-example
